### ISSUE TITLE
Do you have the example for USB Host CDC?

### ISSUE THREAD

**Issue by ziv2013** [tanakamasayuki/EspUsbHost#1]
Hi,

I'm looking for a way to use USB-UART dongle on ESP32-S3. Do you have the demo with USB CDC?

Thanks，

Z.t

**Comment by tanakamasayuki** [comment]
I haven't tried it yet.

https://github.com/touchgadget/esp32-usb-host-demos
I'm using this as a reference.

https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/cdc/cdc_acm_vcp
Is this the CDC?

**Comment by ziv2013** [comment]
OK, thanks a lot. I will study it.
