### ISSUE TITLE
usb/usb_host.h: No such file or directory

### ISSUE THREAD

**Issue by The3ven** [tanakamasayuki/EspUsbHost#5]
Alternatives for usb/usb_host.h: []
ResolveLibrary(usb/usb_host.h)
  -> candidates: []
In file included from C:\Users\Usersname\OneDrive\Documents\Arduino\libraries\EspUsbHost\src/EspUsbHostKeybord.h:4,
                 from C:\Users\Usersname\OneDrive\Documents\Arduino\libraries\EspUsbHost\examples\EspUsbHostKeybord\EspUsbHostKeybord.ino:1:
C:\Users\Usersname\OneDrive\Documents\Arduino\libraries\EspUsbHost\src/EspUsbHost.h:5:10: fatal error: usb/usb_host.h: No such file or directory
 #include <usb/usb_host.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
Using library EspUsbHost at version 1.0.1 in folder: C:\Users\Usersname\OneDrive\Documents\Arduino\libraries\EspUsbHost 
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by tanakamasayuki** [comment]
USB Host cannot be used with ESP32.
Requires ESP32-S3.

**Comment by The3ven** [comment]
sorry i was didn't change the board earlier but now I`m getting error :
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2920
entry 0x403c98d8
E (101612) HUB: Root port reset failed
